Adds support for NSDictionary, NSAray, NSValue and NSString
jpsim/Yams pull request #426
Opened 2024-08-08 15:21 UTC by PopTo

2025-02-17 03:48 UTC, lynchsft requested changes
Hey @PopTo, on the surface this seems reasonable to merge. Could you please add tests that cover all of the new NSObject types and maybe a section to the README that explains the rationale of using NSObject container types?

2025-06-05 07:22 UTC, PopTo commented
Sorry for the delay @lynchsft - things have been hectic. I’ll handle the tests and README update soon.

2025-06-20 15:15 UTC, PopTo commented
@lynchsft Just pushed the tests and README update as discussed — all set now! Thanks for your patience and let me know if you’d like any adjustments.

2025-06-23 18:40 UTC, lynchsft commented
Thank you! I'm gonna work on a bug fix and a repair to the CI today. Then we'll get your PR to green-pass, then a final review. 🤪 Stay tuned.

2025-06-23 19:46 UTC, lynchsft commented
Ok, 6.0.2 was published with the CI fixes. Please rebase/merge and I'll re-run the checks. :)

2025-06-23 21:01 UTC, PopTo commented
Done 🚀 Let’s see how CI likes it now :)

2025-06-26 13:07 UTC, PopTo commented
@lynchsft Is there anything I should still fix or check on my side?

2025-06-29 22:38 UTC, lynchsft commented
@PopTo  There's a set of build error on non-mac platforms that read like so: 
``` 
error: cannot convert value of type '[any NSCopying]' to expected argument type '[NSObject]'
                                            forKeys: ["Clark", "Brian", "Oren"] as [NSCopying])
```

2025-06-29 22:49 UTC, lynchsft requested changes

2025-06-29 22:49 UTC, lynchsft commented on Sources/Yams/Constructor.swift
> +    public static var dynamicMappingMap: MappingMap { [
I'm not sure the word `dynamic` here conveys the meaning. What is more dynamic about these constructors than the other constructors? The types themselves are not more dynamic than corresponding mutable Swift types. 
Maybe, `nsMutableMappingMap` and `nsMutableSequenceMap` ?

2025-06-29 22:49 UTC, lynchsft commented on Sources/Yams/Constructor.swift
> +    public static func construct_set(from mapping: Node.Mapping) -> NSMutableSet? {
Why does NSMutableDictionary have a private function that fulfills the constructor behavior but NSMutableSet performs the work directly here? Unless there is a reason for the variation, please unify the style. :)

2025-06-29 22:49 UTC, lynchsft commented on Sources/Yams/Representer.swift
> +        return .init(floatFormatter.string(for: self)!.replacingOccurrences(of: "+-", with: "-"), Tag(.float))
NSValue can hold far more types of content than just floats. If something in the logic elsewhere is ensuring that these NSValues are indeed floats, please describe that in the comments. If not.... what about the other types of content?

2025-06-29 22:49 UTC, lynchsft commented on Sources/Yams/Representer.swift
> +        return scalar.resolvedTag.name == .str ? scalar : .init(String(self), Tag(.str), .singleQuoted)
I think there's an `.automatic` style here? No? Can't remember. Let's not force the single-quote style if we don't need to.

2025-06-29 22:49 UTC, lynchsft commented on Tests/YamsTests/TestHelper.swift
> +    XCTAssert(actualType == expectedType,
is `YamsAssertEqualType` not available here?

2025-06-29 22:49 UTC, lynchsft commented on Tests/YamsTests/TestHelper.swift
> +        break // For scalars (String, Int, etc.), type already compared
But are the scalar values equal? I think the use of `Any` in the parameters here is suspect. Maybe move the type casting out to the caller?

2025-06-30 15:51 UTC, PopTo commented on Sources/Yams/Constructor.swift
> +    public static var dynamicMappingMap: MappingMap { [
You’re right

2025-06-30 16:32 UTC, PopTo commented on Sources/Yams/Constructor.swift
> +    public static var dynamicMappingMap: MappingMap { [
Yep, Linux things 😉 I’ll check.

2025-06-30 16:37 UTC, PopTo commented on Sources/Yams/Constructor.swift
> +    public static func construct_set(from mapping: Node.Mapping) -> NSMutableSet? {
Haha, fair point! Will refactor for harmony.

2025-06-30 16:41 UTC, PopTo commented on Sources/Yams/Representer.swift
> +        return .init(floatFormatter.string(for: self)!.replacingOccurrences(of: "+-", with: "-"), Tag(.float))
Got it, I’ll review this part — thanks!

2025-07-10 20:45 UTC, PopTo commented
@lynchsft Should be good now — let’s run the tests.

2025-07-10 20:46 UTC, PopTo commented
@lynchsft Should be good now — let’s run the tests.

2025-07-29 18:28 UTC, lynchsft commented on README.md
> +let constructor = Constructor(Constructor.defaultScalarMap,
Needs an update to the new symbol name. (Thank you for changing it.)
I apologize for a long absence. Wanna get this merged. Thank you so much for the contribution. 🙏🏻

2025-08-01 12:37 UTC, PopTo commented on README.md
> +let constructor = Constructor(Constructor.defaultScalarMap,
private_construct_mapping was still lingering in NSMutableDictionary – removed in this commit. Good thing SwiftLint Analyzer is keeping watch 😉

2025-08-08 18:26 UTC, lynchsft commented on README.md
> +                              Constructor.dynamicMappingMap,
```suggestion
                              Constructor.nsMutableMappingMap,
```

2025-08-08 18:26 UTC, lynchsft commented on README.md
> +                              Constructor.dynamicSequenceMap)
```suggestion
                              Constructor.nsMutableSequenceMap)
```

2025-08-09 16:16 UTC, merged

2025-08-09 17:34 UTC, PopTo commented
Thanks for merging, @lynchsft and for the valuable feedback during the review